# Generated by Django 4.1.4 on 2023-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorie_alter_annonce_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(verbose_name=''),
        ),
    ]
