# Generated by Django 4.1.4 on 2023-01-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='prix',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='surface',
            field=models.FloatField(default=0),
        ),
    ]
