# Generated by Django 4.1.4 on 2023-01-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default='', max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.ForeignKey(default=1413, on_delete=django.db.models.deletion.DO_NOTHING, to='api.commune'),
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wilaya'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.wilaya'),
        ),
    ]
