# Generated by Django 4.1.4 on 2023-01-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_adresse_user_commune_user_wilaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.commune'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.wilaya'),
        ),
    ]
