# Generated by Django 4.1.4 on 2023-01-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_commune_alter_user_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='titre',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messgeoffre',
            name='contenu',
            field=models.TextField(default='exit', verbose_name=''),
            preserve_default=False,
        ),
    ]
