# Generated by Django 4.1.4 on 2023-02-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_annonce_titre_messgeoffre_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='messgeoffre',
            name='annonceur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='annonceur_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messgeoffre',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_user', to='api.user'),
        ),
    ]
