# Generated by Django 4.1.4 on 2023-02-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_messgeoffre_annonceur_alter_messgeoffre_emetteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='zoom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
