# Generated by Django 4.1.4 on 2023-02-03 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_annonce_zoom_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='annonce',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.annonce'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
